import type { Metadata } from "next";
import "../globals.css";
import { SocketProvider } from './components/SocketContext'
import { PeerProvider } from './components/PeerContext'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <SocketProvider>
          <PeerProvider>
            {children}
          </PeerProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
